EthereumNetwork:
  #name: "rinkeby"
  name: "mainnet"

RewardsPools:
  - id: "001"
    name: "AFI_Governance"
    network: "rinkeby"
    lpToken: "0x61ad86291Cf96A43265c0c73B219Ae5Fd7ca368b"
    rwToken: ""
    rewardsCtrt: "0xBF76248d5e3bfd1d4dDE4369Fe6163289A0267F6"
    lpTokenPriceSource: ""
    totalLiquiditySource: ""
    loadingTime: 8
    rwTokenPriceSource: "https://info.uniswap.org/pair/0xb6a0d0406772ac3472dc3d9b7a2ba4ab04286891"
    decimalPlace: 18
  - id: "002"
    name: "AFI_Governance"
    network: "mainnet"
    lpToken: "0x68E8A20128e1902C02f533a02eD0cFd8396E3Fbc"
    rwToken: ""
    rewardsCtrt: "0x9cd43309C9E122A13b466391bABC5deC8bE1E01E"
    lpTokenPriceSource: ""
    totalLiquiditySource: ""
    loadingTime: 8
    rwTokenPriceSource: "https://info.uniswap.org/pair/0xb6a0d0406772ac3472dc3d9b7a2ba4ab04286891"
    decimalPlace: 18
  - id: "011"
    name: "UniLP_USDC_AFI"
    network: "mainnet"
    lpToken: ""
    rwToken: ""
    rewardsCtrt: "0xd40cADE3f71C20Ba6FE940E431c890dC100E97d6"
    lpTokenPriceSource: ""
    totalLiquiditySource: ""
    loadingTime: 8
    rwTokenPriceSource: "https://info.uniswap.org/pair/0xb6a0d0406772ac3472dc3d9b7a2ba4ab04286891"
    decimalPlace: 6
  - id: "021"
    name: "afUSDC"
    network: "mainnet"
    lpToken: ""
    rwToken: ""
    rewardsCtrt: "0xAC7DE028cCe2a99e9399aB0bE198Bc950994f50C"
    lpTokenPriceSource: ""
    totalLiquiditySource: ""
    loadingTime: 8
    rwTokenPriceSource: "https://info.uniswap.org/pair/0xb6a0d0406772ac3472dc3d9b7a2ba4ab04286891"
  - id: "031"
    name: "afUSDT"
    network: "mainnet"
    lpToken: ""
    rwToken: ""
    rewardsCtrt: "0x825241bA78700c11a4615523dF4B70F78C7384aa"
    lpTokenPriceSource: ""
    totalLiquiditySource: ""
    loadingTime: 8
    rwTokenPriceSource: "https://info.uniswap.org/pair/0xb6a0d0406772ac3472dc3d9b7a2ba4ab04286891"
    decimalPlace: 6
  - id: "041"
    name: "afiDAI"
    network: "mainnet"
    lpToken: "0x0ea9f8c451f472e9f9463d76097b8d0821cf1a55"
    rwToken: ""
    rewardsCtrt: "0x8667D16150AcAA1FF19AcC5E5c64Bf0Ba1d551b3"
    lpTokenPriceSource: ""
    totalLiquiditySource: ""
    loadingTime: 8
    rwTokenPriceSource: "https://info.uniswap.org/pair/0xb6a0d0406772ac3472dc3d9b7a2ba4ab04286891"
    decimalPlace: 18
